language: java

jdk: oraclejdk7

before_script:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar xzvf android-sdk_r21.1-linux.tgz > /dev/null
  - export ANDROID_HOME=`pwd`/android-sdk-linux/
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android-sdk-linux/tools/android -s update sdk --filter android-16,platform-tool --no-ui
  - android-sdk-linux/tools/android -s update project --path . --target "android-16"

script:
  - ant clean
  - ant release
  - if [ -f ./bin/SABDroidEx-release-unsigned.apk ]; then curl -T ./bin/SABDroidEx-release-unsigned.apk -usabdroidex:2eb633ac0a9b597a8ddae8ddfb422c9799a27fb34087e92bb2ae6dc4ddf1f9f1 https://api.bintray.com/content/sabdroidex/SabdroidEx/SabdroidEx/latest/SABDroidEx.apk; fi